"""
ChatFeedbackStore — SQLite persistence for engineer feedback on chat responses.

Each time an engineer rates a chat assistant reply (👍 or 👎), a ChatFeedbackRow
is appended to this table.  Positive ratings (rating=1) are also indexed into
the Chroma vector store as training signals via ResolutionFeedbackIndexer.

Lifecycle:
  POST /api/v1/chat/feedback  →  ChatFeedbackRepository.record()
  rating == 1                 →  ResolutionFeedbackIndexer.index_chat_feedback()
  Future queries              →  retrieve_chat_feedback_context() injects top-3
                                 relevant past Q&A snippets into the assistant reply
"""
from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlmodel import Field, SQLModel, select


class ChatFeedbackRow(SQLModel, table=True):
    """
    Append-only record of engineer feedback on a single assistant message.

    Fields
    ------
    message_id    : UUID generated by the backend per ChatResponse — stable key
                    that the frontend echoes back when submitting feedback.
    ticket_context: ticket_id the chat was about (if detected from the reply).
    query_text    : The engineer's original question (echoed from the frontend
                    for storage without a separate DB join).
    response_text : The assistant reply that was rated.
    rating        : 1 = positive (helpful), -1 = negative (not helpful).
    comment       : Optional free-text annotation from the engineer.
    engineer_id   : Login string from the request (defaults to 'noc_engineer').
    intent        : Detected intent label at the time of the response.
    created_at    : Immutable insert timestamp.
    """
    __tablename__ = "chat_feedback"

    id:             Optional[int] = Field(default=None, primary_key=True)
    message_id:     str           = Field(..., index=True)
    ticket_context: Optional[str] = None
    query_text:     str
    response_text:  str
    rating:         int           # 1 = positive, -1 = negative
    comment:        Optional[str] = None
    engineer_id:    Optional[str] = None
    intent:         Optional[str] = None
    created_at:     datetime      = Field(default_factory=datetime.utcnow)


class ChatFeedbackRepository:
    """
    Append-only repository for chat feedback rows.

    Never issues UPDATE or DELETE — the table is an immutable audit trail.
    """

    def __init__(self, session) -> None:
        self._session = session

    async def record(self, row: ChatFeedbackRow) -> ChatFeedbackRow:
        """Insert a new feedback row and return it with id + created_at populated."""
        self._session.add(row)
        await self._session.commit()
        await self._session.refresh(row)
        return row

    async def list_recent(self, limit: int = 200) -> list[ChatFeedbackRow]:
        """Return the most recent feedback rows (newest-first)."""
        result = await self._session.execute(
            select(ChatFeedbackRow)
            .order_by(ChatFeedbackRow.created_at.desc())
            .limit(limit)
        )
        return list(result.scalars().all())

    async def get_by_message(self, message_id: str) -> Optional[ChatFeedbackRow]:
        """Return the feedback row for a specific message_id, or None."""
        result = await self._session.execute(
            select(ChatFeedbackRow).where(ChatFeedbackRow.message_id == message_id)
        )
        return result.scalar_one_or_none()
